package Common.GUI;

import Common.db;
import account.settings;
import playlist.*;
import player.GUI.*;
import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import radio.radiologic;

/**
 *
 * @author David, Fionnula
 */
public class PlookifyGUI extends javax.swing.JFrame {

    //currently logged in user
    Account thisUser;
    //search results table
    JTable results;
    //playlist currently selected
    Playlist selectedPlaylist;
    //currently selected track in playlist
    Track selectedTrack;
    Boolean hasSearched = false;
    //arrays to hold indicies of playlist and track objects
    Playlist[] lstPlist;
    Track[] tblTrax;
    //model for playlist list and playlist tracks table
    DefaultTableModel trackmodel = new DefaultTableModel();
    DefaultListModel playlistsModel = new DefaultListModel();
    settings theSettings;

    /**
     * Creates new form mainGUI
     *
     * @param theAccountID
     */
    public PlookifyGUI(int theAccountID) {
        //clear NowPlaylig table in database from previous user
        player.logic.NowPlaying.deleteAll();

        //do GUI setup
        initComponents();

        nowPlayingGUI np = new nowPlayingGUI();
        PlayerGUI p = new PlayerGUI();
        //tell track player who its parent is
        p.setParentFrame(this);
        nowPlaying.add(np);
        playerPanel.add(p);

        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //set up button group        
        searchOptions.add(musicSearch);
        searchOptions.add(friendsSearch);
        searchOptions.add(radioSearch);
        searchOptions.setSelected(musicSearch.getModel(), true);
        //LOGIN
        //get current user through login system
        //thisUser = login.doLogin();//TOTO INTEGRATE ACCOUNTS/LOGIN MODULE

        thisUser = PlaylistLogic.getAccountByAccID(theAccountID);

        if (null == thisUser) {
            //something bad happened so quit
            System.exit(1);
        }
        theSettings = new settings(thisUser);

        //disable radio feature if free user
        if (thisUser.getAccountType() == 'f') {
            tabbed.setEnabledAt(2, false);
            radioSearch.setEnabled(false);
            radioSearch.setText("Subscribe for Radio");
        }
        //get own and friends playlists for this user
        thisUser.playlists = PlaylistLogic.getPlaylistsByAccID(thisUser.getAccountID());
        thisUser.friends = PlaylistLogic.determineFriends(thisUser);

        if (thisUser.playlists != null) {
            //user has at least one playlist so create array
            //  will be used to index objects
            lstPlist = new Playlist[thisUser.playlists.size()];
        }
        //display playlists in list
        refreshPlaylistsList();
        //set playlist info labels
        updateLabels();

        lstPlaylists.setModel(playlistsModel);

        //set up playlist tracks table
        tblplaylistTracks.setModel(trackmodel);
        playlistScroll.setViewportView(tblplaylistTracks);
        //add columns
        //index is will be a hidden column to get the index of a selected track
        //  when it is clicked
        trackmodel.addColumn("index");
        trackmodel.addColumn("Title");
        trackmodel.addColumn("Artist");
        trackmodel.addColumn("Album");
        trackmodel.addColumn("Genre");
        trackmodel.addColumn("Time");
        //remove the index column from the table (it stays on the table model though)
        tblplaylistTracks.removeColumn(tblplaylistTracks.getColumnModel().getColumn(0));

        tblplaylistTracks.setFillsViewportHeight(true);
        //add the rightclick popup listener to the table
        MouseListener popupListener = new RightClickPopupListener();
        tblplaylistTracks.addMouseListener(popupListener);

        //select the first playlist in the playlist list just so something is selected
        try {
            lstPlaylists.setSelectedIndex(0);
        } catch (Exception e) {
            //can't do it - nevermind
        }
        //fit the components properly
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupTrackSelectedFromPlaylist = new javax.swing.JPopupMenu();
        miAddTrackToNowPlaying = new javax.swing.JMenuItem();
        miDeleteTrackFromPlaylist = new javax.swing.JMenuItem();
        popupTrackSelectedFromSearchResults = new javax.swing.JPopupMenu();
        menuAddTrackToPlaylist = new javax.swing.JMenu();
        miAddTrackToNowPlayingFromSearch = new javax.swing.JMenuItem();
        addNP = new javax.swing.JPopupMenu();
        addSong = new javax.swing.JMenuItem();
        addToPlaylist = new javax.swing.JMenu();
        searchOptions = new javax.swing.ButtonGroup();
        radioPopup = new javax.swing.JPopupMenu();
        generate = new javax.swing.JMenuItem();
        top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        musicSearch = new javax.swing.JRadioButton();
        friendsSearch = new javax.swing.JRadioButton();
        radioSearch = new javax.swing.JRadioButton();
        btnAccountSettings = new javax.swing.JButton();
        playerPanel = new javax.swing.JPanel();
        playlistPanel = new javax.swing.JPanel();
        playlist = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPlaylists = new javax.swing.JList();
        lblPlaylists = new javax.swing.JLabel();
        btnNewPlaylist = new javax.swing.JButton();
        btnRenamePlaylist = new javax.swing.JButton();
        btnDeletePlaylist = new javax.swing.JButton();
        tgglbtnChangePlaylistType = new javax.swing.JToggleButton();
        btnPlaySelectedPlaylist = new javax.swing.JButton();
        lblWhosPlaylist = new javax.swing.JLabel();
        lblPlaylistCountAndTime = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nowPlaying = new javax.swing.JPanel();
        friends = new javax.swing.JPanel();
        tabbed = new javax.swing.JTabbedPane();
        playlistScroll = new javax.swing.JScrollPane();
        tblplaylistTracks = new javax.swing.JTable();
        musicScroll = new javax.swing.JScrollPane();
        radioScroll = new javax.swing.JScrollPane();
        radioTable = new javax.swing.JTable();

        miAddTrackToNowPlaying.setText("Add to Now Playing");
        miAddTrackToNowPlaying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddTrackToNowPlayingActionPerformed(evt);
            }
        });
        popupTrackSelectedFromPlaylist.add(miAddTrackToNowPlaying);

        miDeleteTrackFromPlaylist.setText("Remove from playlist");
        miDeleteTrackFromPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDeleteTrackFromPlaylistActionPerformed(evt);
            }
        });
        popupTrackSelectedFromPlaylist.add(miDeleteTrackFromPlaylist);

        menuAddTrackToPlaylist.setText("Add to playlist...");
        popupTrackSelectedFromSearchResults.add(menuAddTrackToPlaylist);

        miAddTrackToNowPlayingFromSearch.setText("Add to Now Playing");
        miAddTrackToNowPlayingFromSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddTrackToNowPlayingFromSearchActionPerformed(evt);
            }
        });
        popupTrackSelectedFromSearchResults.add(miAddTrackToNowPlayingFromSearch);

        addSong.setText("jMenuItem1");
        addSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSongActionPerformed(evt);
            }
        });
        addNP.add(addSong);

        addToPlaylist.setText("Add to Playlist");
        addNP.add(addToPlaylist);

        generate.setText("jMenuItem1");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });
        radioPopup.add(generate);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainFrame"); // NOI18N
        setResizable(false);

        top.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Plookify");

        logOut.setText("Change user");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        search.setForeground(new java.awt.Color(102, 102, 102));
        search.setText("search...");
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                searchPropertyChange(evt);
            }
        });

        musicSearch.setForeground(new java.awt.Color(204, 204, 255));
        musicSearch.setText("Music");

        friendsSearch.setForeground(new java.awt.Color(204, 204, 255));
        friendsSearch.setText("Friends");

        radioSearch.setForeground(new java.awt.Color(204, 204, 255));
        radioSearch.setText("Radio");
        radioSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSearchActionPerformed(evt);
            }
        });

        btnAccountSettings.setText("Account settings");
        btnAccountSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(topLayout.createSequentialGroup()
                        .addComponent(musicSearch)
                        .addGap(18, 18, 18)
                        .addComponent(friendsSearch)
                        .addGap(18, 18, 18)
                        .addComponent(radioSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAccountSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musicSearch)
                    .addComponent(friendsSearch)
                    .addComponent(radioSearch)
                    .addComponent(btnAccountSettings))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        playerPanel.setBackground(new java.awt.Color(0, 51, 51));

        playlist.setBackground(new java.awt.Color(0, 102, 102));

        lstPlaylists.setBackground(new java.awt.Color(0, 102, 102));
        lstPlaylists.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        lstPlaylists.setForeground(new java.awt.Color(255, 255, 255));
        lstPlaylists.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstPlaylists.setMaximumSize(new java.awt.Dimension(169, 378));
        lstPlaylists.setSelectionBackground(new java.awt.Color(0, 51, 51));
        lstPlaylists.setSelectionForeground(new java.awt.Color(153, 204, 255));
        lstPlaylists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lstPlaylistsMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPlaylistsMouseClicked(evt);
            }
        });
        lstPlaylists.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPlaylistsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstPlaylists);

        lblPlaylists.setFont(new java.awt.Font("Gill Sans Nova", 0, 17)); // NOI18N
        lblPlaylists.setForeground(new java.awt.Color(255, 255, 255));
        lblPlaylists.setText("Playlists");

        btnNewPlaylist.setText("New");
        btnNewPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewPlaylistActionPerformed(evt);
            }
        });

        btnRenamePlaylist.setText("Rename");
        btnRenamePlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenamePlaylistActionPerformed(evt);
            }
        });

        btnDeletePlaylist.setText("Delete");
        btnDeletePlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePlaylistActionPerformed(evt);
            }
        });

        tgglbtnChangePlaylistType.setText("Private");
        tgglbtnChangePlaylistType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgglbtnChangePlaylistTypeActionPerformed(evt);
            }
        });

        btnPlaySelectedPlaylist.setText("#play_playlist");
        btnPlaySelectedPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaySelectedPlaylistActionPerformed(evt);
            }
        });

        lblWhosPlaylist.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblWhosPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        lblWhosPlaylist.setText("#playlist owner");

        lblPlaylistCountAndTime.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblPlaylistCountAndTime.setForeground(new java.awt.Color(255, 255, 255));
        lblPlaylistCountAndTime.setText("#tracks and time");

        javax.swing.GroupLayout playlistLayout = new javax.swing.GroupLayout(playlist);
        playlist.setLayout(playlistLayout);
        playlistLayout.setHorizontalGroup(
            playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playlistLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(playlistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playlistLayout.createSequentialGroup()
                        .addComponent(lblPlaylistCountAndTime)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(playlistLayout.createSequentialGroup()
                        .addGroup(playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPlaySelectedPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(playlistLayout.createSequentialGroup()
                                .addComponent(btnNewPlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRenamePlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(playlistLayout.createSequentialGroup()
                                .addComponent(tgglbtnChangePlaylistType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeletePlaylist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(7, 7, 7))))
            .addGroup(playlistLayout.createSequentialGroup()
                .addGroup(playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playlistLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblPlaylists))
                    .addGroup(playlistLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblWhosPlaylist)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        playlistLayout.setVerticalGroup(
            playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playlistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPlaylists)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWhosPlaylist)
                .addGap(7, 7, 7)
                .addComponent(lblPlaylistCountAndTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlaySelectedPlaylist)
                .addGap(7, 7, 7)
                .addGroup(playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewPlaylist)
                    .addComponent(btnRenamePlaylist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(playlistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeletePlaylist)
                    .addComponent(tgglbtnChangePlaylistType))
                .addContainerGap())
        );

        javax.swing.GroupLayout playlistPanelLayout = new javax.swing.GroupLayout(playlistPanel);
        playlistPanel.setLayout(playlistPanelLayout);
        playlistPanelLayout.setHorizontalGroup(
            playlistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        playlistPanelLayout.setVerticalGroup(
            playlistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        nowPlaying.setBackground(new java.awt.Color(0, 102, 102));

        friends.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout friendsLayout = new javax.swing.GroupLayout(friends);
        friends.setLayout(friendsLayout);
        friendsLayout.setHorizontalGroup(
            friendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        friendsLayout.setVerticalGroup(
            friendsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tblplaylistTracks.setAutoCreateRowSorter(true);
        tblplaylistTracks.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        tblplaylistTracks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblplaylistTracks.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblplaylistTracks.setEditingColumn(0);
        tblplaylistTracks.setEditingRow(0);
        tblplaylistTracks.setFillsViewportHeight(true);
        tblplaylistTracks.setGridColor(new java.awt.Color(255, 255, 255));
        tblplaylistTracks.setRowHeight(20);
        tblplaylistTracks.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tblplaylistTracks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblplaylistTracks.setShowVerticalLines(false);
        tblplaylistTracks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblplaylistTracksMouseClicked(evt);
            }
        });
        playlistScroll.setViewportView(tblplaylistTracks);

        tabbed.addTab("Playlists", playlistScroll);
        tabbed.addTab("Search", musicScroll);

        radioTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        radioScroll.setViewportView(radioTable);

        tabbed.addTab("Radio", radioScroll);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nowPlaying, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(friends, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(friends, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nowPlaying, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(playlistPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(playerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playlistPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setUserTitle() {
        this.setTitle("Plookify - User: " + thisUser.getLName()
                + ", " + thisUser.getFName() + " - " + thisUser.getEmail());
    }

    private void addFriendsPlaylists() {
        //if user has any friends
        if (thisUser.friends != null) {
            //for each friend
            for (Account f : thisUser.getFriends()) {
                //if user's friend has any playlists
                if (f.playlists != null) {
                    //for each playlist of each friend
                    for (Playlist p : f.playlists) {
                        //add the playlist to the arraylist 
                        //  this user's playlists
                        thisUser.addPlaylist(p);
                    }
                }
            }
        }
    }

    private void refreshPlaylistsList() {
        //clear model
        playlistsModel.setSize(0);
        //arraylist of current user and current user's friends' playlists
        ArrayList<Playlist> AllPlaylists = new ArrayList<>();
        thisUser.playlists = PlaylistLogic.getPlaylistsByAccID(thisUser.getAccountID());
        //add friends playlists to current user's playlists
        //add the playlists
        addFriendsPlaylists();
        AllPlaylists = thisUser.getPlaylists();

        if (AllPlaylists != null) {
            //index all the playlists
            lstPlist = PlaylistLogic.indexArrayListPlaylist(AllPlaylists);
            //for every playlist
            for (Playlist p : AllPlaylists) {
                //if playlist has at least one track
                if (p.tracks != null) {
                    //add playlist name and total time to list model
                    String listitem = "♫ " + p.getName() + "   -   "
                            + PlaylistLogic.calculatePlaylistTotalTime(p);
                    playlistsModel.addElement(listitem);
                } else {
                    //playlist has no tracks so add name and time (zero) to model
                    String listitem = "♫ " + p.getName() + "   -   00:00";
                    playlistsModel.addElement(listitem);
                }
            }
            addPlaylistsToPopupMenu();
        }

    }

    class PlaylistMenuItem extends JMenuItem {

        //class to extend menu item so it can store a playlist
        //used to get the playlist to which to add a track
        //  when selected by right clicking a search result
        Playlist myPlaylist;

        public void setPlaylist(Playlist p) {
            myPlaylist = p;
        }

        public Playlist getPlaylist() {
            return myPlaylist;
        }
    }

    public void addPlaylistsToPopupMenu() {
        if (addToPlaylist.getComponents() != null) {
            //if (menuAddTrackToPlaylist.getComponentCount() > 1) {
            //clear menu if there are any elements in it already
            addToPlaylist.removeAll();
            //}
        }
        if (thisUser.getPlaylists() != null) {
            for (Playlist p : thisUser.getPlaylists()) {
                //if playlist belongs to current user
                if (p.getOwner() == thisUser.getAccountID()) {
                    PlaylistMenuItem menuItem = new PlaylistMenuItem();
                    menuItem.setPlaylist(p);

                    menuItem.setText(menuItem.getPlaylist().getName());
                    menuItem.addActionListener(new SearchResultsMenuActionListener());
                    addToPlaylist.add(menuItem);
                }
            }
        } else {
            JMenuItem menuItem = new JMenuItem("Create a playlist first");
            menuItem.setEnabled(false);
            addToPlaylist.add(menuItem);
        }
        //re-add the menu options
        addNP.add(addToPlaylist);
    }

    private void repaintPlaylistButtons() {
        //reset all the buttons and label

        lblWhosPlaylist.setText("Playlist by: Me");
        btnRenamePlaylist.setEnabled(true);
        btnDeletePlaylist.setEnabled(true);
        tgglbtnChangePlaylistType.setEnabled(true);
        btnPlaySelectedPlaylist.setText("Add playlist to queue");
        //reset popup menu
        miDeleteTrackFromPlaylist.setEnabled(true);

        if (selectedPlaylist.getType() == 'p') {
            //private playlist so toggle button and set text
            tgglbtnChangePlaylistType.setSelected(false);
            tgglbtnChangePlaylistType.setText("Private");
        } else {
            //shared (public) playlist so set text and untoggle
            tgglbtnChangePlaylistType.setSelected(true);
            tgglbtnChangePlaylistType.setText("Shared");
        }
        if (selectedPlaylist.getOwner() != thisUser.getAccountID()) {
            //this is a shared playlist so disable buttons which could edit 
            //someone else's playlist
            btnRenamePlaylist.setEnabled(false);
            btnDeletePlaylist.setEnabled(false);
            tgglbtnChangePlaylistType.setEnabled(false);
            //disable delete track from playlist popup menu item
            //  because you can't delete tracks from someone else's playlist
            miDeleteTrackFromPlaylist.setEnabled(false);
        }
        if (selectedPlaylist.tracks == null) {
            //playlist has no tracks so disable play button
            btnPlaySelectedPlaylist.setEnabled(false);
        } else {
            btnPlaySelectedPlaylist.setEnabled(true);
        }
    }

    private void updateLabels() {
        //update labels with name of playlist owner and track cound and playlist
        //  total time

        if (selectedPlaylist == null) {
            //user has no playlists
            lblWhosPlaylist.setText("No playlists to display");
            lblPlaylistCountAndTime.setText("");
            tgglbtnChangePlaylistType.setEnabled(false);
            btnRenamePlaylist.setEnabled(false);
            btnDeletePlaylist.setEnabled(false);
            btnPlaySelectedPlaylist.setEnabled(false);
            btnPlaySelectedPlaylist.setText("Play");

            return;
        }
        String lblText = "Playlist by: ";

        if (selectedPlaylist.getOwner() != thisUser.getAccountID()) {
            //not current user's playlist
            lblText += PlaylistLogic.capitalizeFirstLetter(PlaylistLogic.getAccountByAccID(selectedPlaylist.getOwner()).getFName());
        } else {
            //my playlist
            lblText += "Me";
        }
        //set the playoist owner label
        lblWhosPlaylist.setText(lblText);
        //number of tracks in playlist
        if (selectedPlaylist.tracks != null) {
            //if playlist has tracks
            lblText = selectedPlaylist.getTracks().size() + " tracks, ";
        } else {
            //no tracks in playlist
            lblText = "No tracks in playlist.";
            lblPlaylistCountAndTime.setText(lblText);
            return;
        }
        //time of all tracks in playlist
        lblText += PlaylistLogic.calculatePlaylistTotalTime(selectedPlaylist) + " total";
        //set the track info label
        lblPlaylistCountAndTime.setText(lblText);
    }
    private void lstPlaylistsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPlaylistsMousePressed
        tabbed.setSelectedComponent(playlistScroll);
    }//GEN-LAST:event_lstPlaylistsMousePressed

    private void lstPlaylistsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPlaylistsValueChanged
        if (lstPlaylists.getSelectedIndex() == -1) {
            return;
        }
        //get selected playlist object from indexed array of objects
        selectedPlaylist = lstPlist[lstPlaylists.getSelectedIndex()];
        //enable or disable relevant buttons
        repaintPlaylistButtons();
        //update info labels
        updateLabels();
        //reset table
        updateTableTracks();
    }//GEN-LAST:event_lstPlaylistsValueChanged

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed

        player.GUI.PlayerGUI.timer.stop();
        player.GUI.PlayerGUI.slider.setValue(0);
        Common.Main.main(new String[0]);
        this.dispose();


    }//GEN-LAST:event_logOutActionPerformed

    private void updateTableTracks() {
        //clear model
        trackmodel.setRowCount(0);
        //enable incase previously disabled
        tblplaylistTracks.setEnabled(true);
        //add tracks from selected playlist
        if (selectedPlaylist.tracks != null) {
            //index track objects in array
            tblTrax = PlaylistLogic.indexArrayListTrack(selectedPlaylist.tracks);
            //index to keep tracks of rows
            int indx = 0;
            for (Track t : selectedPlaylist.tracks) {
                //add data from the track object
                //also puts indx in the invisible column index
                trackmodel.addRow(new Object[]{indx, t.getTitle(), t.getArtist(),
                    t.getAlbum(), t.getGenre(), PlaylistLogic.formatSecondsToMinutes(t.getTime())});
                //increment indx for next row
                indx++;
            }
        } else {
            //playlist has no tracks so disable table to
            //  avoid null pointers if it's clicked on
            tblplaylistTracks.setEnabled(false);
            trackmodel.setNumRows(0);
        }
        hasSearched = false;
    }

    private void btnRenamePlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenamePlaylistActionPerformed
        //rename playlist given input new name
        if (PlaylistLogic.renamePlaylist(selectedPlaylist, JOptionPane.showInputDialog("Give '" + selectedPlaylist.getName() + "' a new name:"))) {
            refreshPlaylistsList();
        } else {
            PlaylistLogic.dialog("Could not rename playlist.");
        }
    }//GEN-LAST:event_btnRenamePlaylistActionPerformed

    private void tgglbtnChangePlaylistTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgglbtnChangePlaylistTypeActionPerformed
        //try to change playlist type
        if (!PlaylistLogic.changePlaylistType(selectedPlaylist)) {
            //failed
            PlaylistLogic.dialog("Could not change playlist type");
        }
        //update list and buttons
        refreshPlaylistsList();
        repaintPlaylistButtons();
    }//GEN-LAST:event_tgglbtnChangePlaylistTypeActionPerformed

    private void btnNewPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPlaylistActionPerformed
        String newPname = JOptionPane.showInputDialog("Name your new playlist:");
        if (newPname == null) {
            //user didn't type anything
            PlaylistLogic.dialog("Playlist name cannot be empty");
            return;
        }
        //try to create new playlist
        if (PlaylistLogic.createPlaylist(newPname, thisUser)) {
            //success to refresh list
            refreshPlaylistsList();
        } else {
            //failed
            PlaylistLogic.dialog("Could not create playlist.");
        }
    }//GEN-LAST:event_btnNewPlaylistActionPerformed

    class SearchResultsMenuActionListener implements ActionListener {

        //right click on search results to add track or tracks to existing paylist
        @Override
        public void actionPerformed(ActionEvent e) {

            //get the source of the event
            Object source = e.getSource();
            //cast event source to correct type
            PlaylistMenuItem selectedMe = (PlaylistMenuItem) source;
            //get the playlist from the menu selection
            Playlist thePlaylist = selectedMe.getPlaylist();
            //list of track objects selected from table
            ArrayList<Track> selectedTracks = new ArrayList<>();
            //array of row indicies which were selected
            int[] selectedRow;
            //empty album string to enable creation of track objects
            String album = "";
            //get the selected row indicies and add to array
            selectedRow = results.getSelectedRows();
            if (selectedRow.length != 0) {
                for (int i = 0; i < selectedRow.length; i++) {
                    //get the data for each selected row in the table
                    int trackID = (int) results.getValueAt(selectedRow[i], 0);
                    String song = (String) results.getValueAt(selectedRow[i], 1);
                    String artist = (String) results.getValueAt(selectedRow[i], 2);
                    String genre = (String) results.getValueAt(selectedRow[i], 3);
                    int duration = (int) results.getValueAt(selectedRow[i], 4);
                    //create new track object for each selected row
                    Track t = new Track(trackID, song, artist, album, genre, duration);
                    //add track object to list of tracks
                    selectedTracks.add(t);
                }
            }
            //add track to playlist
            for (Track t : selectedTracks) {
                //call playlist logic for each track in list
                PlaylistLogic.addNewTrackToPlaylist(thePlaylist, t);
            }
            //update gui
            refreshPlaylistsList();
            updateLabels();
        }
    }

    class RightClickPopupListener extends MouseAdapter {

        //right click menu on playlist table
        public void mousePressed(MouseEvent e) {
            if (tblplaylistTracks.getSelectedRowCount() < 1) {
                return;
            }
            if (tblplaylistTracks.isFocusOwner()) {
                showPopup(e);
            }
        }

        public void mouseReleased(MouseEvent e) {
            if (tblplaylistTracks.getSelectedRowCount() < 1) {
                return;
            }
            if (tblplaylistTracks.isFocusOwner()) {
                showPopup(e);
            }
        }

        private void showPopup(MouseEvent e) {
            if (tblplaylistTracks.getSelectedRowCount() < 1) {
                //user mouse clicked on a table with no data in so return
                return;
            }
            if (e.isPopupTrigger()) {
                //event is a right click
                if (hasSearched) {
                    //obsolete - remains from playlist standalone gui
                    //show search results menu
                    popupTrackSelectedFromSearchResults.show(e.getComponent(),
                            e.getX(), e.getY());
                } else {
                    //show playlist popup
                    popupTrackSelectedFromPlaylist.show(e.getComponent(),
                            e.getX(), e.getY());
                }
            }
        }
    }

    private void miDeleteTrackFromPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDeleteTrackFromPlaylistActionPerformed
        //delete selected track from playlist
        //  call playlist logic on selected playlist and track
        PlaylistLogic.removeTrackFromPlaylist(selectedPlaylist, selectedTrack);
        //update gui
        updateTableTracks();
        refreshPlaylistsList();
    }//GEN-LAST:event_miDeleteTrackFromPlaylistActionPerformed

    private void miAddTrackToNowPlayingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddTrackToNowPlayingActionPerformed
        //adding single selected track to now playing from playlist table
        //method requires arraylist of tracks even though there's only one
        //  track to add
        ArrayList<Track> toNowPlaying = new ArrayList<>();
        //add single track to arraylist
        toNowPlaying.add(selectedTrack);
        //call playlist logic on arraylist of track
        PlaylistLogic.sendTracksToNowPlaying(toNowPlaying);
        //update gui
        player.GUI.nowPlayingGUI.display();
    }//GEN-LAST:event_miAddTrackToNowPlayingActionPerformed

    private void btnPlaySelectedPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaySelectedPlaylistActionPerformed
        //adding entire playlist to now playing
        //arraylist of track objects
        ArrayList<Track> toNowPlaying = new ArrayList<>();
        for (Track t : selectedPlaylist.tracks) {
            //add each track in playlist to arraylist
            toNowPlaying.add(t);
        }
        //call playlist logic on arraylist of track/tracks
        PlaylistLogic.sendTracksToNowPlaying(toNowPlaying);
        //update gui
        player.GUI.nowPlayingGUI.display();
    }//GEN-LAST:event_btnPlaySelectedPlaylistActionPerformed

    private void btnDeletePlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePlaylistActionPerformed
        //user wishes to delete selected playlist
        //first make sure
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to delete playlist " + selectedPlaylist.getName() + "?",
                "Delete playlist?", JOptionPane.YES_NO_OPTION) > 0) {
            //user not sure so return
            return;
            //user sure so try to delete selected playlist
            //call playlist logic
        } else if (PlaylistLogic.deletePlaylist(selectedPlaylist)) {
            //success so remove from this 
            thisUser.playlists.remove(selectedPlaylist);
            //update gui
            refreshPlaylistsList();
            try {
                //try to select an existing playlist from the list
                //  to cause gui update
                lstPlaylists.setSelectedIndex(0);
            } catch (Exception e) {
                //couldn't so nevermind
                selectedPlaylist = null;
            }
            //update gui
            updateLabels();
        } else {
            //playlist logic couldn't delete playlist
            PlaylistLogic.dialog("Can't delete playlist.");
        }
    }//GEN-LAST:event_btnDeletePlaylistActionPerformed

    private void searchResultsToTrackTable(ArrayList<Track> searchResults) {
        //clear model
        trackmodel.setRowCount(0);
        //enable incase previously disabled
        tblplaylistTracks.setEnabled(true);
        //add tracks from search results
        if (searchResults != null) {
            //index track objects in array
            tblTrax = PlaylistLogic.indexArrayListTrack(searchResults);
            //index to keep tracks of rows
            int indx = 0;
            for (Track t : searchResults) {
                //add data from the track object
                //also puts indx in the invisible column index
                trackmodel.addRow(new Object[]{indx, t.getTitle(), t.getArtist(),
                    t.getAlbum(), t.getGenre(), PlaylistLogic.formatSecondsToMinutes(t.getTime())});
                //increment indx for next row
                indx++;
            }
            //set search results flag to true to help decide which popup menu
            hasSearched = true;
        } else {
            //no search results so inform user and reset table
            tblplaylistTracks.setEnabled(false);
            PlaylistLogic.dialog("No results");
            updateTableTracks();
        }
    }

    private void lstPlaylistsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPlaylistsMouseClicked
        //for when user clicks back onto already selcted playlist
        //otherwise by list selection changed event
        if (!lstPlaylists.isSelectionEmpty()) {
            //as long as some playlist is selected, show 
            //  playlist tracks on table
            updateTableTracks();
            hasSearched = false;
        }
    }//GEN-LAST:event_lstPlaylistsMouseClicked

    private void miAddTrackToNowPlayingFromSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddTrackToNowPlayingFromSearchActionPerformed
        //unused
        ArrayList<Track> toNowPlaying = new ArrayList<>();
        toNowPlaying.add(selectedTrack);
        PlaylistLogic.sendTracksToNowPlaying(toNowPlaying);
    }//GEN-LAST:event_miAddTrackToNowPlayingFromSearchActionPerformed

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        //clear the search box when clicked in
        search.setText("");
    }//GEN-LAST:event_searchFocusGained

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        //user wants to search for something...
        //select search tab if not already selected
        //get the search query
        String searchWord = search.getText();
        //clean up the query
        searchWord = searchWord.trim();
        //decide what the user wants to search through
        if (musicSearch.isSelected()) {
            tabbed.setSelectedComponent(musicScroll);
            //user wants to search for music
            //call track player logic to do search and get results
            results = player.logic.Search.results(searchWord);
            //show results in table
            TableColumn col1 = results.getColumnModel().getColumn(0);
            col1.setMinWidth(0);
            col1.setMaxWidth(0);
            //tblplaylistTracks = results;
            musicScroll.setViewportView(results);
            addSong.setText("Add to Now Playing");
            results.setComponentPopupMenu(addNP);
        } else if (radioSearch.isSelected()) {
            try {
                Connection connection = db.connectToDB();
                radio.radiologic sear = new radio.radiologic();
                ResultSet rs = sear.searchartist(searchWord, connection);
                radioTable.setModel(DbUtils.resultSetToTableModel(rs));
                connection.close();
            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_searchActionPerformed

    private void addSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSongActionPerformed
        player.logic.NowPlaying.nowP(results);
    }//GEN-LAST:event_addSongActionPerformed

    private void tblplaylistTracksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplaylistTracksMouseClicked
        //track selected from playlist tracks table
        //get the row index by looking in the invisible column
        if (selectedPlaylist == null) {
            //user has no playlists to select
            return;
        }
        if (!tblplaylistTracks.isEnabled()) {
            //if the table is disabled don't try to do anything
            return;
        }
        if (tblplaylistTracks.getSelectedRowCount() < 1) {
            //if user has not selected a track yet
            return;
        }
        int selectedTrackIndex = Integer.parseInt(tblplaylistTracks.getModel().getValueAt(tblplaylistTracks.getSelectedRow(), 0).toString());
        if (selectedTrackIndex < 0) {
            //if something has gone wrong just ignore it
            return;
        }
        //pick track from indexed tracks and set as selected track
        selectedTrack = tblTrax[selectedTrackIndex];
        //update popup menu item with playlist name
        miDeleteTrackFromPlaylist.setText("Remove track from " + selectedPlaylist.getName());
    }//GEN-LAST:event_tblplaylistTracksMouseClicked

    private void searchPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_searchPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPropertyChange

    private void radioSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSearchActionPerformed
        tabbed.setSelectedComponent(radioScroll);
        try {
            Connection connection = db.connectToDB();
            radio.radiologic sear = new radio.radiologic();
            ResultSet rs = sear.getartistlist(connection);
            radioTable.setModel(DbUtils.resultSetToTableModel(rs));
            radioTable.setComponentPopupMenu(radioPopup);
            generate.setText("Generate radio");
            connection.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_radioSearchActionPerformed

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        if (generate.getText().equals("Generate radio")) {
            try {
                int row = radioTable.getSelectedRow();
                String values = (radioTable.getModel().getValueAt(row, 0).toString());
                System.out.println(values);
                radiologic gen = new radiologic();
                Connection connection = Common.db.connectToDB();
                ResultSet rs = gen.generateradio(values, connection);
                radioTable.setModel(DbUtils.resultSetToTableModel(rs));
                connection.close();
                generate.setText("Save as playlist");
                for (int count = 0; count < radioTable.getRowCount(); count++) {
                    radio.RadioGUI.idarray[count] = radioTable.getValueAt(count, 0).toString();

                }

            } catch (Exception e) {

            }
        } else {
            try {

                radio.radioplaylist plays = new radio.radioplaylist();
                try {
                    //Connection conn = Common.db.connectToDB();
                    String a = plays.saveradio(thisUser.getEmail());
                     if (!a.equals("no")){
                    plays.addradiosongs(radio.RadioGUI.idarray, a);
                     }
                    refreshPlaylistsList();
                    repaintPlaylistButtons();
                    System.out.println("works");
                } catch (SQLException ex) {
                    //Logger.getLogger(RadioGUI.class.getName()).log(Level.SEVERE, null, ex);
                }

            } catch (NumberFormatException nfe) {
            }
        }
    }//GEN-LAST:event_generateActionPerformed

    private void btnAccountSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountSettingsActionPerformed
        theSettings.setVisible(true);
    }//GEN-LAST:event_btnAccountSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlookifyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlookifyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlookifyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlookifyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                PlookifyGUI plookifyFrame = new PlookifyGUI();
//                plookifyFrame.setVisible(true);
//                plookifyFrame.setTitle("Plookify ");
//                //add logged in user to title
//                plookifyFrame.setTitle();
//                //add image icon
//                ImageIcon img = new ImageIcon("src/Common/media/plookifyLogo.png");
//                plookifyFrame.setIconImage(img.getImage());
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu addNP;
    private javax.swing.JMenuItem addSong;
    private javax.swing.JMenu addToPlaylist;
    private javax.swing.JButton btnAccountSettings;
    private javax.swing.JButton btnDeletePlaylist;
    private javax.swing.JButton btnNewPlaylist;
    private javax.swing.JButton btnPlaySelectedPlaylist;
    private javax.swing.JButton btnRenamePlaylist;
    private javax.swing.JPanel friends;
    private javax.swing.JRadioButton friendsSearch;
    private javax.swing.JMenuItem generate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPlaylistCountAndTime;
    private javax.swing.JLabel lblPlaylists;
    private javax.swing.JLabel lblWhosPlaylist;
    private javax.swing.JButton logOut;
    private javax.swing.JList lstPlaylists;
    private javax.swing.JMenu menuAddTrackToPlaylist;
    private javax.swing.JMenuItem miAddTrackToNowPlaying;
    private javax.swing.JMenuItem miAddTrackToNowPlayingFromSearch;
    private javax.swing.JMenuItem miDeleteTrackFromPlaylist;
    private javax.swing.JScrollPane musicScroll;
    private javax.swing.JRadioButton musicSearch;
    private javax.swing.JPanel nowPlaying;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JPanel playlist;
    private javax.swing.JPanel playlistPanel;
    private javax.swing.JScrollPane playlistScroll;
    private javax.swing.JPopupMenu popupTrackSelectedFromPlaylist;
    private javax.swing.JPopupMenu popupTrackSelectedFromSearchResults;
    private javax.swing.JPopupMenu radioPopup;
    private javax.swing.JScrollPane radioScroll;
    private javax.swing.JRadioButton radioSearch;
    private javax.swing.JTable radioTable;
    private javax.swing.JTextField search;
    private javax.swing.ButtonGroup searchOptions;
    private javax.swing.JTabbedPane tabbed;
    private javax.swing.JTable tblplaylistTracks;
    private javax.swing.JToggleButton tgglbtnChangePlaylistType;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
