package account;

import Common.GUI.PlookifyGUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.*;
import javax.swing.SwingUtilities;
import account.signin;
import playlist.Account;

/**
 *
 * @author tn301
 */
public class settings extends javax.swing.JFrame {

    Connection c = null;
    Statement stmt = null;
    Connection c2 = null;
    Statement stmt2 = null;
    public static String username;
    public static String pass;

    //-db
    public static Account thisUser;

    //-db
    /**
     * Creates new form setting
     *
     * @param theAccount
     */
    public settings(Account theAccount) {
        initComponents();
        thisUser = theAccount;
        username = thisUser.getEmail();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Plookify");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Settings");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Close Account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("Add Device");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("Remove Device");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(107, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2)))
                        .addContainerGap(107, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
        );

        pack();
    }// </editor-fold>                       

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
//            try {
//      Class.forName("org.sqlite.JDBC");
//      c = DriverManager.getConnection("jdbc:sqlite:plookifyDB.sqlite");
//      c.setAutoCommit(false);
//      System.out.println("Opened database successfully");
//
//      stmt = c.createStatement();
//      String sql = "UPDATE ACCOUNT set accountType = 'f' where PAYMENTMISSED = '1' AND PASSWORD = '"+jTextField1.getText()+"';";
//      stmt.executeUpdate(sql);
//      c.commit();
//      System.out.println("Account type checked");
//      JOptionPane.showMessageDialog(null, "Payment Outstanding! Your account is now a free account!");

        this.setVisible(false);

//dispose();
//            new PlookifyGUI().setVisible(true);
//            PlookifyGUI newgui = new PlookifyGUI();
//            
//            JFrame frame = new JFrame("Main");
//            frame.getContentPane().add(newgui);
//            frame.pack();
//            frame.setVisible(true); 
//      stmt.close();
//      c.close();  
// //   System.out.println("Payment Outstanding! Your account is now a free account!");
// //   JOptionPane.showMessageDialog(null, "Payment Outstanding! Your account is now a free account!");
//    //dispose();
//    } catch (Exception e ) {
//      System.err.println( e.getClass().getName() + ": " + e.getMessage() );
//      JOptionPane.showMessageDialog(null, "Incorrect Password!");
//      //System.exit(0);
//    }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

        //-db-
        
        //Should make sure user wants to delete their account
        if (JOptionPane.showConfirmDialog(null, "Are you sure you want to delete your account?",
                "Delete account?", JOptionPane.YES_NO_OPTION) > 0) {
            //user not sure so return
            return;

        }
        //user thinks they're sure so double check
        if (JOptionPane.showConfirmDialog(null, "Are you ABSOLUTELY sure you want to delete your account?",
                "Are you really sure?", JOptionPane.YES_NO_OPTION) > 0) {
            //user doesn't know what they want so don't delete their account
            return;
        }
        
        //user is sure they want to delete their account
        
        //-db-

        try {
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:src/Common/plookifyDB.sqlite");
            c.setAutoCommit(false);
            System.out.println("Opened database successfully");

            stmt = c.createStatement();
            String sql = "DELETE from ACCOUNT where email = '" + username + "';";
            stmt.executeUpdate(sql);
            c.commit();

            stmt.close();
            c.close();
            JOptionPane.showMessageDialog(null,"You have successfully deleted your account.");
            System.exit(0);
        } catch (Exception e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Invalid Password!");
            //System.exit(0);
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Class.forName("org.sqlite.JDBC");
            c2 = DriverManager.getConnection("jdbc:sqlite:src/Common/plookifyDB.sqlite");
            c2.setAutoCommit(false);
            System.out.println("Opened Database Successfully");

            stmt2 = c2.createStatement();
            String sql1 = "UPDATE ACCOUNT set numberDevices = numberDevices+1 where numberDevices<5 AND email = '" + username + "';";
//      String sql; 
//      sql = "SELECT CASE ('numberDevices') when 'password="+jTextField1.getText()+" numberDevices>5' THEN 'numberDevices=numberDevices-1' ELSE 'numberDevices=numberDevices+1' END FROM 'ACCOUNT'";     
//      String newsss = "SELECT CASE ('account') WHEN 'numberDevices>5' THEN 'System.exit(0)' ELSE 'numberDevices = numberDevices+1' END FROM 'ACCOUNT'";
            stmt2.executeUpdate(sql1);
            c2.commit();
            stmt2.close();
            c2.close();
            System.out.println("Device Modified Successfully");
            JOptionPane.showMessageDialog(null, "Device Modified Successfully");
        } catch (Exception e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Invalid Password!");
//      System.exit(0);
        }
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Class.forName("org.sqlite.JDBC");
            c2 = DriverManager.getConnection("jdbc:sqlite:src/Common/plookifyDB.sqlite");
            c2.setAutoCommit(false);
            System.out.println("Opened Database Successfully");

            stmt2 = c2.createStatement();
            String sql1 = "UPDATE ACCOUNT set numberDevices = numberDevices-1 where numberDevices>0 AND email = '" + username + "';";
            stmt2.executeUpdate(sql1);
            c2.commit();
            stmt2.close();
            c2.close();
            System.out.println("Device Modified Successfully");
            JOptionPane.showMessageDialog(null, "Device Modified Successfully");
        } catch (Exception e) {
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Invalid Password!");
//      System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
